name: 'Deploy to AWS Amplify'
description: 'Deploy to AWS Amplify'
inputs:
  region:  
    description: 'Target deploy region'
    required: true
    default: 'ap-southeast-1'
  access-key-id:  
    description: 'Key'
    required: true
    default: ''
  secret-access-key:  
    description: 'Secret'
    required: true
    default: ''
  version:
    description: 'Version'
    required: true
    default: ''
  s3-uri:
    description: 'S3 URI'
    required: true
    default: ''
  app-id:
    description: 'Amplify app ID'
    required: true
    default: ''
  branch:
    description: 'Amplify deploy branch'
    required: true
    default: ''
  static-web-folder:
    description: 'Static web folder to deploy'
    required: true
    default: ''
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_DEFAULT_REGION: ${{ inputs.region }}
    AWS_ACCESS_KEY_ID: ${{ inputs.access-key-id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-access-key }}
    VERSION: ${{ inputs.version }}
    S3_URI: ${{ inputs.s3-uri }}
    AMPLIFY_APP_ID: ${{ inputs.app-id }}
    AMPLIFY_BRANCH_NAME: ${{ inputs.branch }}
    STATIC_WEB_FOLDER: ${{ inputs.static-web-folder }}