name: CI Pipeline

on:
  push:
    branches: [main,develop]
  pull_request:
    branches: [main,develop]

jobs:
  install-and-build:
    name: Install & build project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - run: npm run build
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        env:
          CYPRESS_INSTALL_BINARY: 0
      - run: npm run lint
      - run: npm run test:coverage
        env:
          REACT_APP_EVME_API: https://api-tron-dev.herokuapp.com/graphql
      - name: Report coverage
        uses: vebr/jest-lcov-reporter@v0.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: unit-test-code-coverage
          lcov-file: ./coverage/lcov.info
          update-comment: true
